config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :aggregators do
    resources :sites, only: [:index, :new, :create]
  end

  resources :sites, only: [:show, :edit, :update, :destroy] do 
    member do
      get :test_parse
      patch :change_status
    end

    resources :parse_fields
    resources :parse_items, only: [] do
      member do 
        patch :change_status
        patch :chosen
      end
      collection do
        get :tagged
      end
    end
  end

  resources :tariffs
  get "/payment_sessions/success", to: "payment_sessions#success"
  get "/payment_sessions/cancel", to: "payment_sessions#cancel"
  get "/payment/checkout_session", to: "payment_sessions#checkout_session"


  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :rails_admin do
    get "/tariff/:id/stripe/add", to: "tariffs#add"
    delete "/tariff/:id/stripe/delete", to: "tariffs#delete"
    put "/tariff/:id/stripe/update", to: "tariffs#update"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    set_paginate_params

    @parse_items = UserParseItems.call(current_user, params[:aggregator_id])
    @parse_items = SearchParseItems.call(@parse_items, search_params) if search_params.present?
    @total = @parse_items.count
    
    @parse_items = @parse_items.paginate(@page, @per_page)
    @show_pagination = @total > @page * @per_page
    respond_to do |format|
      format.html {}
      format.json {
        locals = { 
          parse_items: @parse_items, 
          show_pagination: @show_pagination, 
          page: @page 
        }
        render json: {
          content: HomeController.render(partial: "parse_items", locals: locals, layout: false),
        }, status: :ok
      }
    end
  end

  private
  
  def search_params
    params[:search].slice(:title, :created_at, :status, :chosen) if params[:search].present?
  end

  def set_paginate_params
    @per_page = params[:per_page] || 20
    @page = params[:page] || 1
    @page = @page.to_i 
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def link_active?(link_path)
    current_page?(link_path)
  end

  def link_active_to(name = nil, options = nil, html_options = nil, &block)
    html_options[:class] << " active" if link_active?(options)
    link_to(name, options, html_options, &block)
  end
  
  def bell_block
    icon_color = current_user.has_new_items? ? "text-warning" : "text-secondary"
    data_content = "New items: #{current_user.new_items.count}"
    options = {"data-count" => current_user.new_items.count, "data-toggle" => "popover","data-placement" => "bottom", "data-content" => data_content, :class => "#{icon_color} nav-link fa-lg",}
    icon("far", "bell", options)
  end

  def avatar_block
    title_block = content_tag("div", current_user.email, class: "text-center")
    links = [link_to("Profile", edit_user_registration_path, class: "btn btn-profile btn-outline-primary"),
              link_to("Sign out", destroy_user_session_path, class: "btn btn-outline-primary btn-sign-out-js", method: :delete)]
    content_block = content_tag "div", class: "text-center" do |c|
      links.collect { |l| content_tag(:span, l, class: "p-1")}.join.html_safe
    end
    options = {"data-content" => "#{content_block}", "data-toggle" => "popover","data-placement" => "bottom", :title => "#{title_block}", :class => "rounded-circle avatar img-thumbnail", :size => "60x60"} 
    image_tag(avatar_url(current_user), options)
  end
end

app/views/home/_aggregator_selector.haml
- options = options_from_collection_for_select(current_user.aggregators, "id", "title")
= select_tag "aggregator_id", options, class: "form-control aggr-selector", prompt: 'default'

app/views/home/_btn_show_more.haml
- if show_pagination
  .pagination-section
    .btn.btn-outline-warning.btn-lg.btn-show-more{ data: { page: page + 1 }}
      Show more

app/views/home/_btn_up.haml
.btn.btn-outline-primary.btn-up.rounded-circle
  = icon("fas", "arrow-up")

app/views/home/_parse_items.haml
.parse-items.row
  - parse_items.each do |pi|
    .col-lg-6.col-md-6.col-xl-4
      = render partial:  "parse_items/parse_item", locals: { parse_item: pi }
  = render partial: "btn_show_more", locals: { show_pagination: show_pagination, page: page }

app/views/home/index.haml
- if @parse_items.present?
  = render "layouts/search_form"
  = render "aggregator_selector"
  = render partial: "parse_items", locals: { parse_items: @parse_items, page: @page, show_pagination: @show_pagination }
  = render "btn_up"
- else
  .info.text-center.p-5
    %p.lead.text-muted.mx-auto
      You don't have web scrappers now. Folow to 
      = link_to "create your first web scrapper.", new_aggregator_path