config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :aggregators do
    resources :sites, only: [:index, :new, :create]
  end

  resources :sites, only: [:show, :edit, :update, :destroy] do 
    member do
      get :test_parse
      patch :change_status
    end

    resources :parse_fields
    resources :parse_items, only: [] do
      member do 
        patch :change_status
        patch :chosen
      end
      collection do
        get :tagged
      end
    end
  end

  resources :tariffs
  get "/payment_sessions/success", to: "payment_sessions#success"
  get "/payment_sessions/cancel", to: "payment_sessions#cancel"
  get "/payment/checkout_session", to: "payment_sessions#checkout_session"


  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :rails_admin do
    get "/tariff/:id/stripe/add", to: "tariffs#add"
    delete "/tariff/:id/stripe/delete", to: "tariffs#delete"
    put "/tariff/:id/stripe/update", to: "tariffs#update"
  end
end

app/models/site.rb
class Site < ApplicationRecord
  has_many :parse_fields, dependent: :destroy
  has_many :parse_items, dependent: :destroy, foreign_key: "site_id"
  belongs_to :aggregator

  validates :name, presence: true
  validates :url, presence: true,
                  format: { with: /\b((http|https):\/\/?)[^\s()<>]+(?:\([\w\d]+\)|([^[:punct:]\s]|\/?))/ }
  validates :main_selector, presence: true

  accepts_nested_attributes_for :parse_fields, allow_destroy: true, reject_if: proc { |attrs| attrs["name"].blank? }

  scope :active, -> { where(active: true) }
  scope :not_active, -> { where(active: false) }

  def info
    "Name: #{name} Url: #{url} Active: #{active}"
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_aggregator, only: [:new, :index, :create]
  before_action :set_site, except: [:new, :index, :create]
  
  def index
    @sites = @ag.sites.order(:name)
  end

  def new
    @site = @ag.sites.build
  end

  def edit
  end

  def update
    raise ActiveRecord::RecordNotFound if @site.nil?
    respond_to do |format|
      if @site.update(site_params)
        format.js { redirect_to action: 'show', notice: "Site successfuly updated." }
      else
        format.js {
          flash[:alert] = @site.errors.full_messages.first
          flash.discard
          render partial: "shared/error", status: :unprocessable_entity
        }
      end
    end
  end

  def create
    @site = @ag.sites.build(site_params)
    respond_to do |format|
      if @site.save
        format.js { redirect_to action: 'index', notice: "Site successfuly created." }
      else
        format.js {
          flash[:alert] = @site.errors.full_messages.first
          flash.discard
          render partial: "shared/error", status: :unprocessable_entity
        }
      end
    end
  end

  def show
    raise ActiveRecord::RecordNotFound if @site.nil?
  end

  def destroy
    @site.destroy
    respond_to do |format|
      format.js
    end
  end

  def test_parse
    data = Parser.get_data(@site)
    if data.present?
      pi = @site.parse_items.build(data: data[0], status: :new, created_at: Date.today)
      respond_to do |format|
        format.json {
          render json: { content: ParseItemsController.render(template: "sites/_test_parse", locals: { parse_item: pi }, layout: false)}, status: :ok
        }
      end
    else
      respond_to do |format|
        format.json {
          render json: {}, status: :no_content
        }
      end
    end
  end

  def change_status
    if @site.update(active: !@site.active) 
      respond_to do |format|
        format.js {
          render partial: "card-info-update", locals: { site: SiteDecorator.new(@site) }, status: :ok
        }
      end
    end
  end
  private

  def set_site
    site = Site.find(params[:id])
    @site = site if current_user.aggregators.pluck(:id).include?(site.aggregator_id)
  end

  def set_aggregator
    @ag = current_user.aggregators.find(params[:aggregator_id])
  end

  def site_params
    params.require(:site).permit(:name, :url, :main_selector, :active, parse_fields_attributes: [:id, :name, :selector, :_destroy])
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_card-info-update.js.erb
$(".card").replaceWith("<%= j render partial: 'card-info', locals: { site: site }%>")

app/views/sites/_card-info.haml
.card
  .card-header.text-center
    = site.name
  %ul.list-group.list-group-flush
    %li.list-group-item
      = site.url_info
    %li.list-group-item
      .card-status.d-inline
        = site.status_info
  .card-footer.text-center
    = form_with model: Site, url: change_status_site_path(site.id), method: :patch, class: "d-inline site-status-js" do |f|
      = f.submit site.active_btn_title, class: "btn btn-#{site.active_btn_style}"
    .btn.btn-primary.ml-2.test-parse-js{data: { url: test_parse_site_path(site.id) }} 
      Test parse

app/views/sites/_form.haml
.row
  .col-8.offset-2
    - path = aggregator_sites_path(@ag) if @ag.present?
    = form_with model: @site, url: path do |f|
      .form-group
        .row
          .col
            = f.text_field :name, class: "form-control", placeholder: "Name"
          .col.field__description
            = "Name for site parse items will be have this tag"
      .form-group
        .row
          .col
            = f.text_field :url, class: "form-control", placeholder: "Url"
          .col.field__description
            = "Url it where places blocks/elements that you want parse"
      .form-group
        .row
          .col
            = f.text_field :main_selector, class: "form-control", placeholder: "Block selector"
          .col.field__description
            = "Block selector it css element for find every parse block/element"
      .form-group
        = link_to_add_association 'Add parse field', f, :parse_fields
        %table.table.parse_fields
          %caption Parse Fields* - (info what does mean parse field)
          %thead
            %tr
              %td
                Name
              %td
                Selector
              %td
                Action
          %tbody
            = f.fields_for(:parse_fields) do |pf|
              = render 'parse_field_fields', f: pf
        
      .form-group
        = f.submit "Save", class: "btn btn-primary"

app/views/sites/_parse_field_fields.haml
%tr.nested-fields
  %td
    = f.text_field :name, class: "form-control"
  %td
    = f.text_field :selector, class: "form-control"
  %td
    = link_to_remove_association "Remove", f

app/views/sites/_test_parse.haml
= render partial: "parse_items/parse_item", locals: { parse_item: parse_item }

app/views/sites/edit.haml
= render "form"

app/views/sites/edit.js.erb
$('.alert').html("<%= j render partial: "errors", locals: { resource: resource } %>")
$('.alert').fadeIn()
setTimeout(flashMessage, 10000)
function flashMessage(){
  $('.alert').fadeOut()
}

app/views/sites/index.haml
%table.table.table-hover
  %thead.thead-light
    %tr
      %th
        Name
      %th
        Url
      %th.text-center
        Actions
      %th.text-center
        Active
  %tbody
    - @sites.each_with_index do |site|
      %tr
        %td
          = site.name
        %td
          = site.url
        %td.text-center
          = link_to "Setting", site_path(site), class: "btn btn-secondary"
          = link_to "Edit", edit_site_path(site), class: "btn btn-secondary"
          = link_to "Delete", site_path(site), method: :delete, class: "btn btn-danger delete-site", remote: true
        %td.text-center
          - if site.active?
            = icon("fas", "check text-success")
          - else
            = icon("fas", "ban text-danger")
= link_to "Add Site", new_aggregator_site_path(@ag), class: "btn btn-primary"

app/views/sites/new.haml
= render "form"

app/views/sites/show.haml
.row
  .col-4.left-column
    = render partial: "card-info", locals: { site: SiteDecorator.new(@site) }
  .col-8
    %table.table.table-hover
      %thead.thead-light
        %tr
          %th
            Name
          %th
            Selector
          %th
            Actions
      %tbody
        - @site.parse_fields.each do |pf|
          %tr
            %td
              = pf.name
            %td
              = pf.selector
            %td
              = link_to "Edit", edit_site_parse_field_path(@site, pf), class: "btn btn-secondary"
              = link_to "Delete", site_parse_field_path(@site, pf), method: :delete, remote: true, class: "btn btn-danger delete-parse-field"
    = link_to "Add Parse setting", new_site_parse_field_path(@site), class: "btn btn-primary"
    
    