config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :aggregators do
    resources :sites, only: [:index, :new, :create]
  end

  resources :sites, only: [:show, :edit, :update, :destroy] do 
    member do
      get :test_parse
      patch :change_status
    end

    resources :parse_fields
    resources :parse_items, only: [] do
      member do 
        patch :change_status
        patch :chosen
      end
      collection do
        get :tagged
      end
    end
  end

  resources :tariffs
  get "/payment_sessions/success", to: "payment_sessions#success"
  get "/payment_sessions/cancel", to: "payment_sessions#cancel"
  get "/payment/checkout_session", to: "payment_sessions#checkout_session"


  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  namespace :rails_admin do
    get "/tariff/:id/stripe/add", to: "tariffs#add"
    delete "/tariff/:id/stripe/delete", to: "tariffs#delete"
    put "/tariff/:id/stripe/update", to: "tariffs#update"
  end
end

app/views/layouts/_datepicker.haml
.input-group
  %input#datepicker.form-control{placeholder: "Added date", type: "text" }
  .input-group-append
    .input-group-text
      = icon("far", "calendar-alt")

app/views/layouts/_errors.html.erb
<ul>
  <% resource.errors.full_messages.each do |message| %> 
    <li class='error'>
      <%= "#{message}" %>
    </li>
  <% end %>
</ul>

app/views/layouts/_flash.haml
- if flash[:alert]
  .alert.alert-danger.p-3.text-center
    = flash[:alert]
- if flash[:notice]
  .alert.alert-success.p-3.text-center
    = flash[:notice]

app/views/layouts/_footer.haml
%footer.footer.mt-5.text-center.text-muted
  .container
    © 2020 Ctulhuweb

app/views/layouts/_header.haml
.header.container-fluid.box-shadow.border-bottom
  %nav.row.p-2.navbar-expand-lg.navbar-expand-md.navbar.navbar-light.bg-light.align-middle
    %h5.navbar-brand
      World Agregetor
    %button.navbar-toggler{"aria-controls" => "navbarToggler", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarToggler", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarToggler.collapse.navbar-collapse
      %ul.navbar-nav.my-0.ml-auto.mr-2
        %li.nav-item
          = link_active_to "Aggregators", aggregators_path, class: "nav-link"
        %li.nav-item
          = link_active_to "Tariffs", tariffs_path, class: "nav-link"
        %li.nav-item
          = link_active_to "Home", root_path, class: "nav-link"
      - if user_signed_in?
        = bell_block
        = avatar_block
      - else
        = link_to "Sign in", new_user_session_path, class: "nav-link btn btn-outline-primary"
  - if action_name == "index" && controller_name == "home" && @parse_items.present?
    = button_tag(class: "btn-open-search btn btn-outline-primary mr-3 border-top-0 rounded-0") do
      = icon('fas', 'search')

app/views/layouts/_search_form.haml
= form_with(url: root_path, method: :get, class: "search-form", local: true) do |f|
  .row
    .col
      = f.text_field :title, placeholder: "Title", class: "form-control"
    .col.input-group
      = f.text_field :created_at, class: "form-control", id: "datepicker", placeholder: "Added date"
      .input-group-append
        .input-group-text
          = icon("far", "calendar-alt")
    .col
      - options = ParseItem.statuses.map { |c| [c.first, c.first] }
      = f.select :status, options_for_select(options), { prompt: "select" }, { class: "form-control" } 
    .col.d-flex.align-items-center
      .custom-control.custom-checkbox
        = f.check_box :chosen, { class: "custom-control-input", id: "defaultUnchecked" }, true, false
        = f.label :chosen, class:"custom-control-label", for: "defaultUnchecked"

app/views/layouts/_stripe_form.haml
%form#payment-form{:action => "/charge", :method => "post"}
  .form-card
    %label{:for => "card-element"}
      Credit or debit card
    #card-element
      / A Stripe Element will be inserted here.
    / Used to display form errors.
    #card-errors{:role => "alert"}
  %button.btn.btn-primary Submit Payment

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WorldAgregator
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = action_cable_meta_tag
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}
    %script{ src: "https://js.stripe.com/v3/" }
    %link{href:"https://fonts.googleapis.com/css?family=Bellota+Text&display=swap&subset=cyrillic", rel:"stylesheet"}
  %body
    = render "layouts/header"
    = render "layouts/flash"
    .container.h-100.pt-4
      = yield
    = render "layouts/footer"
    -# %script{:crossorigin => "", :src => "https://unpkg.com/react@16/umd/react.development.js"}
    -# %script{:crossorigin => "", :src => "https://unpkg.com/react-dom@16/umd/react-dom.development.js"}
    -# = javascript_pack_tag "button_like", 'data-turbolinks-track': 'reload'
    %script{:crossorigin => "anonymous", :integrity => "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"}

app/views/layouts/errors.js.erb
$('.alert').html("<%= j render partial: "layouts/errors", locals: { resource: resource } %>")
$('.alert').fadeIn()
setTimeout(flashMessage, 10000)
function flashMessage(){
  $('.alert').fadeOut()
}